// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmwFyys6oZyMYVO0S1emkFCKTAP7peUYo',
    appId: '1:607359533803:web:d0594f69d89d59701ff4ae',
    messagingSenderId: '607359533803',
    projectId: 'todolist-e53a3',
    authDomain: 'todolist-e53a3.firebaseapp.com',
    storageBucket: 'todolist-e53a3.appspot.com',
    measurementId: 'G-25LD59K2PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjBx5D08CLE3OQRkwiljqXslNsTiDQTzw',
    appId: '1:607359533803:android:84e540dfe4d937f21ff4ae',
    messagingSenderId: '607359533803',
    projectId: 'todolist-e53a3',
    storageBucket: 'todolist-e53a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhSUQHjUBXUiP_w7P7LSD3XBG9K_rz9so',
    appId: '1:607359533803:ios:4422c3d3c05dddcb1ff4ae',
    messagingSenderId: '607359533803',
    projectId: 'todolist-e53a3',
    storageBucket: 'todolist-e53a3.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
